### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by blackxored** [neilff/redux-ui-router#28] opened 2015-11-20 15:59 UTC
``` javascript
import angular from 'angular';
import 'angular-ui-router';
import ngRedux from 'ng-redux';
import ngReduxUiRouter from 'redux-ui-router';

// ...

angular.module('app', [
  ngRedux,
  ngReduxUiRouter,
  'ngMaterial',
  'ngAnimate',
 // ...
).
```

**Comment by dheerajvs** [comment] 2015-11-27 15:31
I'm getting this issue too.
I guess this could happen when you're using a different version of angular than what is mentioned as a peer dependency for redux-ui-router. In my case, I'm using Ionic's version of Angular.

**Comment by neilff** [comment] 2015-12-02 18:52
Will take a look this week and see what is going on, thanks for the heads up

**Comment by dheerajvs** [comment] 2015-12-05 16:26
I resolved the issue by requiring Angular separately instead of using the one [bundled with Ionic](https://github.com/driftyco/ionic/blob/master/release/js/ionic.bundle.js).

**Comment by xlozinguez** [comment] 2016-09-18 22:20
This happened to me, the reason was that I was loading the app both with `ng-app="app"` specified on the body tag and using the `angular.bootstrap` method in the index.js file (or whatever your main app file is.

**Comment by jongunter** [comment] 2017-05-01 20:22
This happens to me, too. I'm embedding this library from a `<script>` tag rather than using module loader like webpack (legacy .NET environment..lol).  It seems as though the entire angular library is accidentally bundled in `/dist/redux-ui-router.js`.

**Comment by hally9k** [comment] 2017-05-02 00:45
@jongunter I have just released new version with fixed bundles that should fix your issue. Let me know if it fixes your issue or not.

**Comment by jongunter** [comment] 2017-05-08 22:33
Thanks for getting that fixed. I'm now getting the following error, unfortunately:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ng-ui-router-middleware due to:
Error: [$injector:modulerr] Failed to instantiate module undefined due to:
Error: [ng:areq] Argument 'module' is not a function, got undefined
```

**Comment by skortchmark9** [comment] 2017-06-01 20:24
Same issue here.

**Comment by skortchmark9** [comment] 2017-06-01 21:05
Figured it out, ui router started shipping stuff as an npm org and they changed their namespace. The bundled code is looking for ```angular-ui-router``` on the window. This fixes it:
```
        <script src="/node_modules/@uirouter/core/_bundles/ui-router-core.min.js"></script>
        <script src="/node_modules/@uirouter/angularjs/release/ui-router-angularjs.min.js"></script>
        <script>window['angular-ui-router'] = window["@uirouter/angularjs"]</script>
```

**Comment by hally9k** [comment] 2017-06-18 20:20
@skortchmark9 Just to clarify, when you say the bundled code you mean the redux-ui-router bundle? I'm trying to reproduce this on my end, could you give an example or some further detail?

**Comment by skortchmark9** [comment] 2017-06-20 02:04
Yep that's right. So for me that's
```
<script src="/node_modules/redux-ui-router/dist/redux-ui-router.js"></script>
```

**Comment by hally9k** [comment] 2017-06-23 21:14
I dont use the bundle, it's quite a new addition and admittedly It should probably have some testing wrapped around it... @kaidjohnson what's your take on this? Is the bundle 'sketchy'??

**Comment by kaidjohnson** [comment] 2017-06-24 12:54
@skortchmark9 it sounds like you're bundling redux-ui-router from the window object rather than including it in your bundle through import or require. My team just implemented UI Router (1.0.4) and Redux UI Router (0.7.1) via `<script>` tags without issue. Not sure you need to hand off `window['@uirouter/angular.js']` like that. I get the sense that this is the bit that you're finding sketchy? The 0.7.* track of redux UI Router seems to be aware of the UI Router library changes and is working as expected for us without this extra step.

The pre-bundled version of Redux UI Router is for standalone usage, eg apps that aren't [yet] bundling their projects and instead running scripts in the window as we used to before browserify and webpack cane along. This requires access to Redux UI Router (and other libs) via the window object:

`angular.module('myApp', [window.ngReduxUiRouter.default);`

If you're bundling your app and want to include redux ui router, you won't want to include the lib via a script tag. Instead use import or require (pointing at source, not the bundled lib) to include the lib as part of your bundle:

```
import ngReduxUiRouter from '/path/to/redux-ui-route/src/index.js'

angular.module('myApp', [ngReduxUiRouter]);
```

(note this example may not be exact. Meant to clarify the approach, but the details may be off. I can't recall off the top of my head what format this lib gets imported as)

**Comment by skortchmark9** [comment] 2017-06-24 23:21
I'm not bundling my app, I am referring to the bundle in the published npm package for this repo: ```node_modules/redux-ui-router/dist/redux-ui-router.js```.
It's currently 12k lines unminified:
```bash
cat node_modules/redux-ui-router/dist/redux-ui-router.js | wc -l
12891
```
And contains lines like:
```
var mod_main = angular_1.ng.module('ui.router', ['ui.router.init', 'ui.router.state', 'ui.router.angular1']);
```
*That's* what I was saying is sketchy, since stuff like that should be in ui router's bundle, not ```redux-ui-router```'s

I was under the impression that when building a bundle for the browser with webpack that it would look for dependencies on the window object instead of inlining all 100~ish of them. I'm not really familiar with webpack though so I could be wrong.

Regardless, I'm pretty sure the bundle *used* to look for stuff on the window object ( I don't think I ever noted the version, sorry), and that's why I (and presumably others on this thread) experienced the issue.

**Comment by kaidjohnson** [comment] 2017-06-25 00:20
Thanks for the clarification. I see what you mean. We did remove angular core from the redux-ui-router bundle, but I guess ui-router core is still in there. Looking at the code, I realize I had accounted for `angular-ui-router`, but the ui-router namespace change didn't propagate to the webpack config. This should be a simple fix. Putting together a PR now...

**Comment by kaidjohnson** [comment] 2017-06-25 00:45
The redux-ui-router unminified is back down to ~2000 lines, and no longer contains these two dependency libraries within it. They will need to be provided separately.

This config worked for us with these updates:

```
<script src="/path/to/angular/angular.min.js"></script>
<script src="/path/to/@uirouter/angularjs/release/angular-ui-router.min.js"></script>
<script src="/path/to/redux-ui-router/dist/redux-ui-router.min.js"></script>
<script src="/path/to/my/app.js"></script>
```

```
angular.module('myApp', ['ui.router', window.ngReduxUiRouter.default]);
```

@skortchmark9 good catch! And thanks again for the clarification!

**Comment by hally9k** [comment] 2017-06-25 22:19
v0.7.2 released. Closing for now.

**Closed by hally9k** 2017-06-25 22:19 UTC
